# Generated by Django 4.1.7 on 2023-03-05 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("fromvia", models.TextField()),
                ("description", models.TextField()),
                (
                    "certficate_path",
                    models.FileField(blank=True, upload_to="files/certificates"),
                ),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.FileField(upload_to="files/cv")),
            ],
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.TextField(editable=False)),
                ("subject", models.TextField(editable=False)),
                ("message", models.TextField(editable=False)),
                ("datetimee", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PrimarySkills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("img", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("duration", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SecondarySkills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("percentage", models.CharField(max_length=100)),
                (
                    "primaryskillsname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.primaryskills",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("tools", models.TextField()),
                ("image_path", models.ImageField(upload_to="files/images")),
                ("report_path", models.FileField(blank=True, upload_to="files/report")),
                ("priority", models.IntegerField(default=0)),
                ("live_link", models.URLField(blank=True, null=True)),
                ("git_link", models.URLField(blank=True, null=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        null=True, related_name="tags", to="main.tags"
                    ),
                ),
            ],
        ),
    ]
