# Generated by Django 4.1.2 on 2023-10-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='target',
            field=models.TextField(blank=True, default='web', null=True),
        ),
    ]
